name: build-test
on: [push]
jobs:
  build-for-ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt upgrade
      - run: sudo apt install libopencv-dev
      - run: cmake . 
      - run: make .
  
  build-for-ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt upgrade
      - run: sudo apt install libopencv-dev
      - run: cmake . 
      - run: make .

