name: build-test
on: [push]
jobs:
  build-for-ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: Dovyski/setup-opencv-action@v1.1
        with:
          opencv-version: '4.2.0'
      - run: cmake . 
      - run: make .
  
  build-for-ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt remove x264 libx264-dev -y
      - run: sudo apt install -y build-essential checkinstall git cmake pkg-config yasm git gfortran libjpeg8-dev libjasper1 libjasper-dev libpng-dev libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev libxine2-dev libv4l-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev qt5-default libgtk2.0-dev libtbb-dev libatlas-base-dev libfaac-dev libmp3lame-dev libtheora-dev libvorbis-dev libxvidcore-dev libopencore-amrnb-dev libopencore-amrwb-dev libtbb2 libtiff-dev python-dev python-numpy x264 v4l-utils
      - uses: Dovyski/setup-opencv-action@v1.1
        with:
          opencv-version: '4.2.0'
          install-deps: false
      - run: cmake . 
      - run: make .

